server:
  port: 9999
  error:
    whitelabel:
      enabled: false

spring:
  h2:
    console:
      enabled: true
  r2dbc:
    url: r2dbc:h2:file://../data/keeper;MODE=MySQL
    username: sa
    password: password
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
    path: /api

jwt:
  key: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    com.querydsl.sql: DEBUG
